# Essentials:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amadeusw.com" # the base hostname & protocol for your site
markdown: redcarpet

# Footer:
title: Amadeus' blog
myname: Amadeusz Wieczorek
bio: > # this means to ignore newlines until "baseurl:"
  Co-founder and developer of Alive, every C# developers' personal assistant.
aliveurl: http://comealive.io
description: 
twitter_username: HiAmadeus
github_username:  AmadeusW
