# Essentials:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amadeusw.com" # the base hostname & protocol for your site
markdown: kramdown

# Footer:
title: Amadeusz Wieczorek
bio: > # this means to ignore newlines until "baseurl:"
  I'm a computer engineer. I love programming,
  the great outdoors, and hacking on hardware projects. 
  I'm a co-founder of Alive, showing C# developers 
  exactly what their code does, as they write it:
aliveurl: http://comealive.io
twitter_username: HiAmadeus
github_username:  AmadeusW
