title = 'Amadeus'
theme = 'ama'
baseURL = '//amadeusw.com'
languageCode = 'en-us'

[params]
  title = "Amadeo's website"
  shortTitle = "Amadeo's"
  footerName = '//AW'
  summary = "projects programming travel"
