title = 'Amadeus'
theme = 'ama'
baseURL = '//amadeusw.com'
languageCode = 'en-us'

[params]
  title = 'Amadeo'
  footerName = 'Amadeus Wieczorek'
  footerAbbr = 'Pronounce: A-ma-de-ows Vee-cho-reck'
  footerDescription = 'I supercharge your productivity.'
